// Цветовая схема для ассемблера

// 1. Комментарии (Зеленый) — имеют высший приоритет
#6A9955 ;.*

// 2. Операторы (Синий)
#569CD6 \b(load|stor|add|addi|inc|sub|subd|dec|mul|div|and|or|not|jmp|je|jl|jg|jne|cls)\b

// 3. Регистры (Оранжевый)
#CE9178 \b(OUT|IR|MAR|MDR|AC|PC|F)\b

// 4. Адреса (Светло-зеленый)
#B5C6A8 \b0x[0-9a-f]+\b